version: "3"
services:
  sajermann-fornite:
    image: "ghcr.io/sajermann/sf-sajermannfortnite/bot:latest"
    restart: always
    build: .
    environment:
      - TOKEN={{ secrets.TOKEN }}
      - URL_FORTNITEAPI={{ secrets.URL_FORTNITEAPI }}
      - TOKEN_FORTNITEAPI={{ secrets.TOKEN_FORTNITEAPI }}

