services:
  sajermann-fornite:
    image: "ghcr.io/sajermann/sf-sajermannfortnite/bot:latest"
    restart: always
    build:
      context: .
      target: builder # Remove para usar estágio final
    environment:
      - NODE_ENV=production