version: "3"
services:
  sajermann-fornite:
    image: "ghcr.io/sajermann/sf-sajermannfortnite/bot:latest"
    restart: always
    build: .
    environment:
      - TOKEN=OTc5MzQzNTY1NDI5ODEzMjU4.GBybDV.Xp6xnKYzEySh_MDmE4Urk--1Kt3Pf-yHGC1vkk
      - URL_FORTNITEAPI=https://fortniteapi.io/v1/
      - TOKEN_FORTNITEAPI=cfd7397c-80de7a8b-f469060b-708fdf00

