version: "3.8"
services:
  sajermann-fornite:
    image: "ghcr.io/sajermann/sf-sajermannfortnite/bot:latest"
    restart: always
    build:
      context: .
      args: 
        - batata={{secrets.FRITA}}
        - TOKEN={{secrets.TOKEN}}
        - URL_FORTNITEAPI={{secrets.URL_FORTNITEAPI}}
        - TOKEN_FORTNITEAPI={{secrets.TOKEN_FORTNITEAPI}}
    # environment:
    #   - URL_FORTNITEAPI={{ secrets.URL_FORTNITEAPI }}
    #   - TOKEN_FORTNITEAPI={{ secrets.TOKEN_FORTNITEAPI }}
    #   - BRUNO=SAJERMANN


