name: CI-SajermannFortnite

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USERNAME }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}

    - name: Replace Variables
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "{{secrets.TOKEN}}"
        replace: "${{secrets.TOKEN}}"
        regex: false
        include: "**docker-compose.yml"
    - name: Replace Variables
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "{{secrets.URL_FORTNITEAPI}}"
        replace: "${{secrets.URL_FORTNITEAPI}}"
        regex: false
        include: "**docker-compose.yml"
    - name: Replace Variables
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "{{secrets.TOKEN_FORTNITEAPI}}"
        replace: "${{secrets.TOKEN_FORTNITEAPI}}"
        regex: false
        include: "**docker-compose.yml"
    - name: Replace Variables
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "{{secrets.FRITA}}"
        replace: "frita"
        regex: false
    
    # Build Bot 
    - run: |
        docker-compose -f bot/docker-compose.yml build 
        ls
        docker tag ghcr.io/sajermann/sf-sajermannfortnite/bot:latest ghcr.io/sajermann/sf-sajermannfortnite/bot:${{ github.sha }}
    - run: |
        docker push ghcr.io/sajermann/sf-sajermannfortnite/bot:latest
        docker push ghcr.io/sajermann/sf-sajermannfortnite/bot:${{ github.sha }}
